theme = "relearn"
baseURL = 'https://okawak.github.io/artemis_crib/'
languageCode = 'en-us'
title = 'CRIB artemis'

googleAnalytics = "G-MZF67K577Y"
enableGitInfo = true

[params]
  editURL = "https://github.com/okawak/artemis_crib/tree/pages-build/content/"
  themeVariant = "artemis_crib"
  alwaysopen = false
  author = "Kodai Okawa"
  disableMathJax = false
  customMathJaxURL = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
  mathJaxInitialize = "{}"
  highlightWrap = true
  disableLandingPageButton = true

#[frontmatter]
#  lastmod = ":fileModTime"


# For search functionality
[outputs]
  home = [ "HTML", "RSS", "SEARCH", "PRINT", "SEARCHPAGE"]
  section = ["HTML", "RSS", "PRINT"]
  page = ["HTML", "RSS", "PRINT"]


[markup]
  [markup.highlight]
    lineNumbersInTable = false
    guessSyntax = false
    noClasses = true
    style = "monokai"

# For menu extra shortcuts
[[menu.shortcuts]]
  name = "<i class='fab fa-fw fa-github'></i> Our GitHub repo"
  identifier = "ds"
  url = "https://github.com/okawak/artemis_crib"
  weight = 10
[[menu.shortcuts]]
  name = "<i class='fas fa-fw fa-bookmark'></i> Hugo Documentation"
  identifier = "hugodoc"
  url = "https://gohugo.io/"
  weight = 20
[[menu.shortcuts]]
  name = "<i class='fas fa-fw fa-tags'></i> Tags"
  url = "tags/"
  weight = 30

