theme = "relearn"
baseURL = 'https://okawak.github.io/artemis_crib/'
#canonifyURLs = true
#relativeURLs = true
languageCode = 'en-us'
title = 'CRIB artemis'
summaryLength = 10

googleAnalytics = "G-MZF67K577Y"
enableGitInfo = true

[params]
editURL = "https://github.com/okawak/artemis_crib/tree/pages-build/content/"
alwaysopen = false
author.name = "Kodai Okawa"
disableMathJax = false
customMathJaxURL = "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
mathJaxInitialize = "{}"
highlightWrap = true
disableLandingPageButton = true

themeVariant = [
  { identifier = "CRIB-theme", name = "CRIB-theme" },
  { identifier = "zen-dark" },
  { identifier = "learn" },
  { identifier = "relearn-dark" },
]


#[frontmatter]
#  lastmod = ":fileModTime"


# For search functionality
[outputs]
home = ["HTML", "RSS", "SEARCH", "PRINT", "SEARCHPAGE"]
section = ["HTML", "RSS", "PRINT"]
page = ["HTML", "RSS", "PRINT"]


[markup]
[markup.highlight]
lineNumbersInTable = false
guessSyntax = false
noClasses = false
style = "monokai"

# For menu extra shortcuts
[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-file-code-o'></i> Source Code"
url = "docs/html"
weight = 30
[[menu.shortcuts]]
name = "<i class='fas  fa-home'></i> CRIB homepage"
url = "https://www.cns.s.u-tokyo.ac.jp/crib/crib-new/"
weight = 5
[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repository"
identifier = "ds"
url = "https://github.com/okawak/artemis_crib"
weight = 10
[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-bookmark'></i> Hugo Documentation"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20
[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-tags'></i> Tags"
url = "tags/"
weight = 30
